ci:
  autoupdate_schedule: weekly
  autofix_prs: true
  autofix_commit_msg: "[pre-commit.ci] autofix"
  autoupdate_branch: main
  autoupdate_commit_msg: "[pre-commit.ci] autoupdate"

default_language_version:
  python: python3.14

default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args:
          - --py3-plus
          - --py38-plus
          - --py39-plus
          - --py310-plus
          - --py311-plus
          - --py312-plus
          - --py313-plus
          - --py314-plus
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
      - id: mypy
        additional_dependencies: [types-pyyaml, pydantic]
        exclude: ^(/manifest.*|docs/|scripts/)
  - repo: https://github.com/JelleZijlstra/autotyping
    rev: 24.9.0
    hooks:
      - id: autotyping
        stages: [pre-commit]
        types: [python]
        args: [--safe]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.16
    hooks:
      - id: ruff-check
        args:
          - --fix
          - --show-fixes
          - --unsafe-fixes
          - --preview
          - --target-version py314
          - --extend-select
          - --output-format=github
        types_or:
          - python
          - pyi
      - id: ruff-format
        types_or:
          - python
          - pyi

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args:
          - --allow-multiple-documents
          - --unsafe
        exclude: ^(docs/|scripts/)
      - id: check-json
      - id: check-toml
      - id: check-ast
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-builtin-literals
      - id: check-symlinks
      - id: pretty-format-json
        args:
          - --autofix
        exclude: ^(custom_components/jackery_solarvault/manifest.*|tests/|docs/|scripts/)
      - id: fix-byte-order-marker
      - id: detect-private-key
      - id: destroyed-symlinks
      
  - repo: https://github.com/cheickmec/smellcheck
    rev: v0.3.1
    hooks:
      - id: smellcheck
        args: ['--fail-on', 'warning']
