[pytest]
testpaths = tests
norecursedirs = .git .pytest_cache __pycache__ pytest-cache-files-*
pythonpath = .
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning:pytest_homeassistant_custom_component
    ignore::DeprecationWarning:homeassistant
    ignore::DeprecationWarning:aiohttp
    ignore::DeprecationWarning:voluptuous
