"""Protocol reference coverage map for Jackery SolarVault.

This module maps entries from ``docs/jackery_complete_reference.json`` to the
integration implementation that consumes or builds them. Tests intentionally
load the reference and fail when a new protocol element is neither mapped nor
explicitly exempted.
"""

from typing import Final

HTTP_ENDPOINTS: Final[dict[str, str]] = {
    "api/agreeUpgrade": "client/_endpoints/misc.py:async_agree_privacy_consent",
    "api/alarm": "client/_endpoints/statistics.py:async_get_alarm",
    "api/alarm/detail": "client/_endpoints/misc.py:async_get_alarm_detail",
    "api/diy/gcsList": "client/_endpoints/misc.py:async_get_gcs_list",
    "api/diy/zoneList": "client/_endpoints/misc.py:async_get_zone_list",
    "api/faq/answer": "client/_endpoints/misc.py:async_get_faq_answer",
    "api/faqList": "client/_endpoints/misc.py:async_get_faq_list",
    "api/file/feedback": "client/_endpoints/misc.py:async_submit_feedback",
    "api/instruction": "client/_endpoints/misc.py:async_get_product_instruction",
    "api/isUpgradeRequired": "client/_endpoints/misc.py:async_check_privacy_update",
    "api/push/configGet": "client/_endpoints/push.py:async_get_push_config",
    "api/push/configSet": "client/_endpoints/push.py:async_set_push_config",
    "api/push/notifyList": "client/_endpoints/push.py:async_get_notify_list",
    "api/push/unreadCount": "client/_endpoints/push.py:async_get_unread_count",
    "app/banner/list": "client/_endpoints/misc.py:async_get_banner_list",
    "app/version/getNewVersion": "client/_endpoints/misc.py:async_check_app_version",
    "auth/cancel": "client/_endpoints/auth.py:async_cancel_account",
    "auth/check_verification": "client/_endpoints/auth.py:async_check_verification_code",
    "auth/headimg": "client/_endpoints/auth.py:async_upload_headimg",
    "auth/login": "client/_endpoints/auth.py:async_login",
    "auth/loginOut": "client/_endpoints/auth.py:async_logout",
    "auth/modifyInfo": "client/_endpoints/auth.py:async_update_user_info",
    "auth/modifyPassword": "client/_endpoints/auth.py:async_reset_password",
    "auth/register": "client/_endpoints/auth.py:async_register",
    "auth/updateRegisterId": "client/_endpoints/auth.py:async_update_register_id",
    "auth/verificationCode": "client/_endpoints/auth.py:async_send_verification_code",
    "device/accept_bind": "client/_endpoints/device.py:async_accept_shared_device",
    "device/accessories": "client/_endpoints/accessories.py:async_get_accessories",
    "device/accessories/exist": "client/_endpoints/accessories.py:async_check_accessories_exist",
    "device/accessories/exists": "client/_endpoints/accessories.py:async_check_jackery_accessories_exist",
    "device/accessories/list": "client/_endpoints/accessories.py:async_get_accessories_list",
    "device/accessories/name": "client/_endpoints/accessories.py:async_set_accessories_name",
    "device/accessories/synchronizeSmartAccessoriesData": "client/_endpoints/accessories.py:async_sync_smart_accessories",
    "device/alert": "client/_endpoints/misc.py:async_sync_alerts",
    "device/battery/pack/list": "client/_endpoints/device.py:async_get_battery_pack_list",
    "device/bind": "client/_endpoints/device.py:async_bind_device",
    "device/bind/list": "client/_endpoints/device.py:async_list_devices_legacy",
    "device/bind/nickname": "client/_endpoints/device.py:async_set_device_nickname",
    "device/bind/remove": "client/_endpoints/device.py:async_remove_shared_access",
    "device/bind/removeAll": "client/_endpoints/device.py:async_remove_all_shared_access",
    "device/bind/share/list": "client/_endpoints/device.py:async_get_device_shared_managers",
    "device/bind/shared": "client/_endpoints/device.py:async_get_device_shared_list",
    "device/chargeReport": "client/_endpoints/device.py:async_get_charge_report",
    "device/currencies/bindCurrency": "client/_endpoints/energy_price.py:async_bind_currency",
    "device/currencies/currencyList": "client/_endpoints/energy_price.py:async_get_currency_list",
    "device/currencies/deviceCurrency": "client/_endpoints/energy_price.py:async_get_device_currency",
    "device/deviceMaxPowerRecord/saveRecord": "client/_endpoints/device.py:async_set_max_power",
    "device/dynamic/cancelContractAuth": "client/_endpoints/energy_price.py:async_cancel_contract_auth",
    "device/dynamic/contractList": "client/_endpoints/energy_price.py:async_get_contract_list",
    "device/dynamic/dynamicPrice": "client/_endpoints/energy_price.py:async_get_dynamic_price",
    "device/dynamic/historyConfig": "client/_endpoints/energy_price.py:async_get_price_history_config",
    "device/dynamic/loginUrl": "client/_endpoints/energy_price.py:async_get_dynamic_price_login_url",
    "device/dynamic/powerPriceConfig": "client/_endpoints/energy_price.py:async_get_power_price",
    "device/dynamic/priceCompany": "client/_endpoints/energy_price.py:async_get_price_sources",
    "device/dynamic/saveContractAuth": "client/_endpoints/energy_price.py:async_save_contract_auth",
    "device/dynamic/saveDynamicMode": "client/_endpoints/energy_price.py:async_set_dynamic_mode",
    "device/dynamic/saveLocationId": "client/_endpoints/energy_price.py:async_save_location_id",
    "device/dynamic/saveSingleMode": "client/_endpoints/energy_price.py:async_set_single_mode",
    "device/location": "client/_endpoints/device.py:async_get_location",
    "device/offline/stat": "client/_endpoints/misc.py:async_get_offline_statistics",
    "device/ota/bluetooth": "client/_endpoints/device.py:async_get_ble_ota_link",
    "device/ota/list": "client/_endpoints/device.py:async_get_ota_info",
    "device/ota/update": "client/_endpoints/device.py:async_start_ota_update",
    "device/ota/version/list": "client/_endpoints/device.py:async_get_ble_ota_versions",
    "device/property": "client/_endpoints/device.py:async_get_device_property",
    "device/property/power3": "client/_endpoints/misc.py:async_get_power3",
    "device/property/pv": "client/_endpoints/device.py:async_modify_pv_name",
    "device/property/subShadow": "client/_endpoints/accessories.py:async_get_sub_shadow",
    "device/property/systemShadow": "client/_endpoints/accessories.py:async_get_system_shadow",
    "device/shelly/binding/failures": "client/_endpoints/shelly.py:async_get_shelly_binding_failures",
    "device/shelly/devices": "client/_endpoints/shelly.py:async_get_shelly_devices",
    "device/smartMode/checkIfSet": "client/_endpoints/smart_mode.py:async_check_smart_mode_set",
    "device/smartMode/getSmartMode": "client/_endpoints/smart_mode.py:async_get_smart_mode_info",
    "device/smartMode/startSmartMode": "client/_endpoints/smart_mode.py:async_start_smart_mode",
    "device/stat": "client/_endpoints/statistics.py:async_get_box_stat",
    "device/stat/battery": "client/_endpoints/statistics.py:async_get_device_battery_stat",
    "device/stat/carbon": "client/_endpoints/statistics.py:async_get_carbon_stat",
    "device/stat/ct": "client/_endpoints/statistics.py:async_get_device_ct_stat",
    "device/stat/ct/statics": "client/_endpoints/statistics.py:async_get_portable_ct_stat",
    "device/stat/cutoff": "client/_endpoints/statistics.py:async_get_cutoff_stat",
    "device/stat/deviceStatistic": "client/_endpoints/statistics.py:async_get_device_statistic",
    "device/stat/eps": "client/_endpoints/statistics.py:async_get_device_eps_stat",
    "device/stat/getSmartSchedulePrediction": "client/_endpoints/statistics.py:async_get_smart_schedule_prediction",
    "device/stat/meter": "client/_endpoints/statistics.py:async_get_device_meter_stat",
    "device/stat/onGrid": "client/_endpoints/statistics.py:async_get_device_home_stat",
    "device/stat/profit": "client/_endpoints/statistics.py:async_get_profit_stat",
    "device/stat/pv": "client/_endpoints/statistics.py:async_get_device_pv_stat",
    "device/stat/smartSocketStatistic": "client/_endpoints/statistics.py:async_get_device_socket_statistic",
    "device/stat/soc": "client/_endpoints/statistics.py:async_get_soc_stat",
    "device/stat/socket": "client/_endpoints/statistics.py:async_get_device_socket_stat",
    "device/stat/symmetry": "client/_endpoints/statistics.py:async_get_symmetry_stat",
    "device/stat/sys/battery/trends": "client/_endpoints/statistics.py:async_get_battery_trends",
    "device/stat/sys/home/trends": "client/_endpoints/statistics.py:async_get_home_trends",
    "device/stat/sys/pv/trends": "client/_endpoints/statistics.py:async_get_pv_trends",
    "device/stat/systemStatistic": "client/_endpoints/statistics.py:async_get_system_statistic",
    "device/stat/today": "client/_endpoints/statistics.py:async_get_today_energy",
    "device/system": "client/_endpoints/device.py:async_create_system",
    "device/system/deviceName": "client/_endpoints/device.py:async_modify_device_name",
    "device/system/exist": "client/_endpoints/device.py:async_check_system_bound",
    "device/system/list": "client/_endpoints/device.py:async_get_system_list",
    "device/system/name": "client/_endpoints/device.py:async_set_system_name",
    "device/tou/queryTouPlan": "client/_endpoints/energy_price.py:async_query_tou_plan",
    "device/tou/saveTouPlan": "client/_endpoints/energy_price.py:async_save_tou_plan",
    "device/unbind": "client/_endpoints/device.py:async_unbind_device",
    "user/info": "client/_endpoints/auth.py:async_get_user_info",
    "wss-cloud/device/shelly/auth-url": "client/_endpoints/shelly.py:async_get_shelly_auth_url",
    "wss-cloud/device/shelly/device/control": "client/_endpoints/shelly.py:async_control_shelly_device",
    "wss-cloud/device/shelly/device/realtime-power": "client/_endpoints/shelly.py:async_get_shelly_realtime_power",
    "wss-cloud/device/shelly/unbind/account": "client/_endpoints/shelly.py:async_unbind_shelly_account",
    "wss-cloud/device/shelly/unbind/device": "client/_endpoints/shelly.py:async_unbind_shelly_device",
}

HTTP_ENDPOINT_EXEMPTIONS: Final[dict[str, str]] = {
    "auth/generatedJwt": "Mobile-app-only account/content flow or not required for Home "
    "Assistant SolarVault runtime.",
    "device/bind/qrcode": "Mobile-app-only account/content flow or not required for Home "
    "Assistant SolarVault runtime.",
    "device/bluetoothKey": "Mobile-app-only account/content flow or not required for Home "
    "Assistant SolarVault runtime.",
}

MQTT_MESSAGE_HANDLERS: Final[dict[str, str]] = dict.fromkeys(
    (
        "DevicePropertyChange",
        "QueryDeviceProperty",
        "ControlCombine",
        "QueryCombineData",
        "QuerySubDeviceGroupProperty",
        "ControlSubDevice",
        "BindSmartAccessory",
        "RemoveSmartAccessory",
        "DownloadDeviceSchedule",
        "QueryWeatherPlan",
        "SendWeatherAlert",
        "CancelWeatherAlert",
        "UploadDeviceAlert",
        "QueryWifiConfig",
        "ThirdPartMQTTConfig",
        "QueryThirdPartMQTTConfig",
        "QueryElectricityStrategy",
        "InsertElectricityStrategy",
        "UpdateElectricityStrategy",
        "DeleteElectricityStrategy",
        "QueryCurrentElectricityStrategy",
        "SetBatteryBoundry",
        "TOUSchedule",
        "QueryTOUSchedule",
        "QueryCircuitProperty",
    ),
    "handlers/mqtt_handlers.py:normalize_local_mqtt_payload",
)

COMMAND_BUILDERS: Final[dict[str, str]] = {
    "3001": "client/mqtt_command.py:command_body_for_transport",
    "3002": "client/mqtt_command.py:command_body_for_transport",
    "3003": "client/mqtt_command.py:command_body_for_transport",
    "3004": "client/mqtt_command.py:command_body_for_transport",
    "3005": "client/mqtt_command.py:command_body_for_transport",
    "3006": "client/mqtt_command.py:command_body_for_transport",
    "3007": "client/mqtt_command.py:command_body_for_transport",
    "3008": "client/mqtt_command.py:command_body_for_transport",
    "3009": "client/mqtt_command.py:command_body_for_transport",
    "3010": "client/mqtt_command.py:command_body_for_transport",
    "3011": "client/mqtt_command.py:command_body_for_transport",
    "3012": "client/mqtt_command.py:command_body_for_transport",
    "3013": "client/mqtt_command.py:command_body_for_transport",
    "3014": "client/mqtt_command.py:command_body_for_transport",
    "3015": "client/mqtt_command.py:command_body_for_transport",
    "3016": "client/mqtt_command.py:command_body_for_transport",
    "3017": "client/mqtt_command.py:command_body_for_transport",
    "3018": "client/mqtt_command.py:command_body_for_transport",
    "3019": "client/mqtt_command.py:command_body_for_transport",
    "3020": "client/mqtt_command.py:command_body_for_transport",
    "3021": "client/mqtt_command.py:command_body_for_transport",
    "3022": "client/mqtt_command.py:command_body_for_transport",
    "3023": "client/mqtt_command.py:command_body_for_transport",
    "3024": "client/mqtt_command.py:command_body_for_transport",
    "3025": "client/mqtt_command.py:command_body_for_transport",
    "3026": "client/mqtt_command.py:command_body_for_transport",
    "3027": "client/mqtt_command.py:command_body_for_transport",
    "3028": "client/mqtt_command.py:command_body_for_transport",
    "3029": "client/mqtt_command.py:command_body_for_transport",
    "3030": "client/mqtt_command.py:command_body_for_transport",
    "3031": "client/mqtt_command.py:command_body_for_transport",
    "3032": "client/mqtt_command.py:command_body_for_transport",
    "3033": "client/mqtt_command.py:command_body_for_transport",
    "3034": "client/mqtt_command.py:command_body_for_transport",
    "3035": "client/mqtt_command.py:command_body_for_transport",
    "3036": "client/mqtt_command.py:command_body_for_transport",
    "3037": "client/mqtt_command.py:command_body_for_transport",
    "3038": "client/mqtt_command.py:command_body_for_transport",
    "3039": "client/mqtt_command.py:command_body_for_transport",
    "3040": "client/mqtt_command.py:command_body_for_transport",
    "3041": "client/mqtt_command.py:command_body_for_transport",
    "3042": "client/mqtt_command.py:command_body_for_transport",
    "3043": "client/mqtt_command.py:command_body_for_transport",
    "3044": "client/mqtt_command.py:command_body_for_transport",
    "3045": "client/mqtt_command.py:command_body_for_transport",
    "3046": "client/mqtt_command.py:command_body_for_transport",
    "3047": "client/mqtt_command.py:command_body_for_transport",
}

COMMAND_NAME_BUILDERS: Final[dict[str, str]] = {
    "BIND_SMART_PART": "client/mqtt_command.py:command_body_for_transport",
    "CONTROL_AC_OFF_GRID_SWITCH": "client/mqtt_command.py:command_body_for_transport",
    "CONTROL_MAX_OUT_PW": "client/mqtt_command.py:command_body_for_transport",
    "CONTROL_REBOOT": "client/mqtt_command.py:command_body_for_transport",
    "CONTROL_STANDBY": "client/mqtt_command.py:command_body_for_transport",
    "DEVICE_GET_OTA_PAGE_DATA": "client/mqtt_command.py:command_body_for_transport",
    "FAULT_ALARM_REPORT": "client/mqtt_command.py:command_body_for_transport",
    "GET_DEVICE_OTA_VERSION": "client/mqtt_command.py:command_body_for_transport",
    "GET_THIRD_PARTY_MQTT_CONFIG": "client/mqtt_command.py:command_body_for_transport",
    "GET_TIME_ZONE": "client/mqtt_command.py:command_body_for_transport",
    "GET_WIFI_CONFIG": "client/mqtt_command.py:command_body_for_transport",
    "NOTIFY_DEVICE_CAN_OTA": "client/mqtt_command.py:command_body_for_transport",
    "NOTIFY_DEVICE_OTA_TOTAL_PAGE": "client/mqtt_command.py:command_body_for_transport",
    "READ_DEVICE_INFO": "client/mqtt_command.py:command_body_for_transport",
    "READ_SUB_DEVICE_BATTERY_PACK": "client/mqtt_command.py:command_body_for_transport",
    "READ_SUB_DEVICE_COMBO": "client/mqtt_command.py:command_body_for_transport",
    "READ_SUB_DEVICE_CT": "client/mqtt_command.py:command_body_for_transport",
    "READ_SUB_DEVICE_METER_HEAD": "client/mqtt_command.py:command_body_for_transport",
    "READ_SUB_DEVICE_SOCKET": "client/mqtt_command.py:command_body_for_transport",
    "READ_SYSTEM_INFO": "client/mqtt_command.py:command_body_for_transport",
    "READ_WIFI_LIST": "client/mqtt_command.py:command_body_for_transport",
    "SEND_TIME_ZONE": "client/mqtt_command.py:command_body_for_transport",
    "SET_CHARGE_DISCHARGE_LINE": "client/mqtt_command.py:command_body_for_transport",
    "SET_THIRD_PARTY_MQTT_CONFIG": "client/mqtt_command.py:command_body_for_transport",
    "SUB_CONTROL_SOCKET_PRI_ENABLE": "client/mqtt_command.py:command_body_for_transport",
    "SUB_CONTROL_SOCKET_SWITCH": "client/mqtt_command.py:command_body_for_transport",
    "SUB_SET_CT_SCHEDULE_PHASE": "client/mqtt_command.py:command_body_for_transport",
    "SYNC_GRID_STANDARD": "client/mqtt_command.py:command_body_for_transport",
    "SYNC_MQTT_CONNECT_INFO": "client/mqtt_command.py:command_body_for_transport",
    "SYSTEM_CONTROL_AUTO_STANDBY": "client/mqtt_command.py:command_body_for_transport",
    "SYSTEM_CONTROL_OFF_GRID_AUTO_SHUTDOWN": "client/mqtt_command.py:command_body_for_transport",
    "SYSTEM_DELETE_STORM_EVENT": "client/mqtt_command.py:command_body_for_transport",
    "SYSTEM_GET_STORM_EVENT": "client/mqtt_command.py:command_body_for_transport",
    "SYSTEM_SET_DEFAULT_LOAD_POWER": "client/mqtt_command.py:command_body_for_transport",
    "SYSTEM_SET_FEED_GRID_POWER": "client/mqtt_command.py:command_body_for_transport",
    "SYSTEM_SET_FOLLOW_METER": "client/mqtt_command.py:command_body_for_transport",
    "SYSTEM_SET_OFF_GRID_SHUTDOWN_TIME": "client/mqtt_command.py:command_body_for_transport",
    "SYSTEM_SET_STORM_EVENT": "client/mqtt_command.py:command_body_for_transport",
    "SYSTEM_SET_TEMP_UNIT": "client/mqtt_command.py:command_body_for_transport",
    "SYSTEM_SET_WORK_MODEL": "client/mqtt_command.py:command_body_for_transport",
    "SYSTEM_STORM_EVENT_SWITCH": "client/mqtt_command.py:command_body_for_transport",
    "TIMER_TASK_ADD": "client/mqtt_command.py:command_body_for_transport",
    "TIMER_TASK_DELETE": "client/mqtt_command.py:command_body_for_transport",
    "TIMER_TASK_READ": "client/mqtt_command.py:command_body_for_transport",
    "TIMER_TASK_UPDATE": "client/mqtt_command.py:command_body_for_transport",
    "UNBIND_SMART_PART": "client/mqtt_command.py:command_body_for_transport",
    "WRITE_WIFI_INFO": "client/mqtt_command.py:command_body_for_transport",
}

COMMAND_EXEMPTIONS: Final[dict[str, str]] = {
    "1": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "10": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "11": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "12": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "13": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "14": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "17": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "18": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "19": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "2": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "20": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "21": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "22": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "23": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "24": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "25": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "26": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "27": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "28": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "29": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "3": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "30": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "31": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "32": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "33": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "34": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "35": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "36": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "37": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "38": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "39": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "4": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "40": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "41": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "42": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "43": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "5": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "6": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "7": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "8": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
    "9": "Mobile app portable power-station command; SolarVault home integration "
    "intentionally does not expose portable commands.",
}

DTO_FIELD_CONSUMERS: Final[dict[str, str]] = {
    "AccBaseBody.ip": "ingest.py:merge_live_properties",
    "AccBaseBody.mac": "ingest.py:merge_live_properties",
    "AccBaseBody.name": "ingest.py:merge_live_properties",
    "AccBaseBody.rssi": "ingest.py:merge_live_properties",
    "AccBaseBody.sn": "ingest.py:merge_live_properties",
    "AccBaseBody.ssid": "ingest.py:merge_live_properties",
    "AccBaseBody.type": "ingest.py:merge_live_properties",
    "AccBaseBody.version": "ingest.py:merge_live_properties",
    "AccCTBody.ap": "ingest.py:merge_live_properties",
    "AccCTBody.ap1": "ingest.py:merge_live_properties",
    "AccCTBody.ap2": "ingest.py:merge_live_properties",
    "AccCTBody.ap3": "ingest.py:merge_live_properties",
    "AccCTBody.curr": "ingest.py:merge_live_properties",
    "AccCTBody.curr1": "ingest.py:merge_live_properties",
    "AccCTBody.curr2": "ingest.py:merge_live_properties",
    "AccCTBody.curr3": "ingest.py:merge_live_properties",
    "AccCTBody.fact": "ingest.py:merge_live_properties",
    "AccCTBody.fact1": "ingest.py:merge_live_properties",
    "AccCTBody.fact2": "ingest.py:merge_live_properties",
    "AccCTBody.fact3": "ingest.py:merge_live_properties",
    "AccCTBody.freq": "ingest.py:merge_live_properties",
    "AccCTBody.power": "ingest.py:merge_live_properties",
    "AccCTBody.power1": "ingest.py:merge_live_properties",
    "AccCTBody.power2": "ingest.py:merge_live_properties",
    "AccCTBody.power3": "ingest.py:merge_live_properties",
    "AccCTBody.rep": "ingest.py:merge_live_properties",
    "AccCTBody.rep1": "ingest.py:merge_live_properties",
    "AccCTBody.rep2": "ingest.py:merge_live_properties",
    "AccCTBody.rep3": "ingest.py:merge_live_properties",
    "AccCTBody.volt": "ingest.py:merge_live_properties",
    "AccCTBody.volt1": "ingest.py:merge_live_properties",
    "AccCTBody.volt2": "ingest.py:merge_live_properties",
    "AccCTBody.volt3": "ingest.py:merge_live_properties",
    "AccMeterStatApi.path": "stats/__init__.py:normalize_stat_response",
    "AccMeterStatApi.response.chargingEnergy": "stats/__init__.py:normalize_stat_response",
    "AccMeterStatApi.response.dischargingEnergy": "stats/__init__.py:normalize_stat_response",
    "AccSocketBody.op": "ingest.py:merge_live_properties",
    "AccSocketBody.sc": "ingest.py:merge_live_properties",
    "AccSocketBody.switch": "ingest.py:merge_live_properties",
    "AccSocketBody.ts": "ingest.py:merge_live_properties",
    "AccSocketStatApi.path": "stats/__init__.py:normalize_stat_response",
    "AccSocketStatApi.response.unit": "stats/__init__.py:normalize_stat_response",
    "AccSocketStatApi.response.useEnergy": "stats/__init__.py:normalize_stat_response",
    "AccSocketStatApi.response.x": "stats/__init__.py:normalize_stat_response",
    "AccSocketStatApi.response.y": "stats/__init__.py:normalize_stat_response",
    "AiSmartScheduleApi.path": "stats/__init__.py:normalize_stat_response",
    "AiSmartScheduleApi.response.currency": "stats/__init__.py:normalize_stat_response",
    "AiSmartScheduleApi.response.days": "stats/__init__.py:normalize_stat_response",
    "AiSmartScheduleApi.response.homeList": "stats/__init__.py:normalize_stat_response",
    "AiSmartScheduleApi.response.priceList": "stats/__init__.py:normalize_stat_response",
    "AiSmartScheduleApi.response.profit": "stats/__init__.py:normalize_stat_response",
    "AiSmartScheduleApi.response.pvPowerList": "stats/__init__.py:normalize_stat_response",
    "AiSmartScheduleApi.response.xList": "stats/__init__.py:normalize_stat_response",
    "AtsEleStatApi.path": "stats/__init__.py:normalize_stat_response",
    "AtsEleStatApi.response.n": "stats/__init__.py:normalize_stat_response",
    "AtsEleStatApi.response.p": "stats/__init__.py:normalize_stat_response",
    "AtsEleStatApi.response.totalN": "stats/__init__.py:normalize_stat_response",
    "AtsEleStatApi.response.totalP": "stats/__init__.py:normalize_stat_response",
    "AtsEleStatApi.response.unit": "stats/__init__.py:normalize_stat_response",
    "AtsEleStatApi.response.x": "stats/__init__.py:normalize_stat_response",
    "BatteryPackBody.deviceSn": "ingest.py:merge_live_properties",
    "BatteryPackBody.ec": "ingest.py:merge_live_properties",
    "BatteryPackBody.ip": "ingest.py:merge_live_properties",
    "BatteryPackBody.isFirmwareUpgrade": "ingest.py:merge_live_properties",
    "BatteryPackBody.it": "ingest.py:merge_live_properties",
    "BatteryPackBody.op": "ingest.py:merge_live_properties",
    "BatteryPackBody.ot": "ingest.py:merge_live_properties",
    "BatteryPackBody.rb": "ingest.py:merge_live_properties",
    "BatteryPackBody.version": "ingest.py:merge_live_properties",
    "BatteryPackSub.batSoc": "ingest.py:merge_live_properties",
    "BatteryPackSub.cellTemp": "ingest.py:merge_live_properties",
    "BatteryPackSub.inPw": "ingest.py:merge_live_properties",
    "BatteryPackSub.isFirmwareUpgrade": "ingest.py:merge_live_properties",
    "BatteryPackSub.outPw": "ingest.py:merge_live_properties",
    "BatteryPackSub.version": "ingest.py:merge_live_properties",
    "BatteryStatApi.path": "stats/__init__.py:normalize_stat_response",
    "BatteryStatApi.response.totalCharge": "stats/__init__.py:normalize_stat_response",
    "BatteryStatApi.response.totalDischarge": "stats/__init__.py:normalize_stat_response",
    "BatteryStatApi.response.unit": "stats/__init__.py:normalize_stat_response",
    "BatteryStatApi.response.x": "stats/__init__.py:normalize_stat_response",
    "BatteryStatApi.response.y": "stats/__init__.py:normalize_stat_response",
    "BatteryStatApi.response.y1": "stats/__init__.py:normalize_stat_response",
    "BatteryStatApi.response.y2": "stats/__init__.py:normalize_stat_response",
    "BatteryStatApi.response.y3": "stats/__init__.py:normalize_stat_response",
    "BindSmartBean.bindKey": "ingest.py:merge_live_properties",
    "BindSmartBean.devType": "ingest.py:merge_live_properties",
    "BindSmartBean.deviceSn": "ingest.py:merge_live_properties",
    "BindSmartBean.linkType": "ingest.py:merge_live_properties",
    "BindSmartBean.param": "ingest.py:merge_live_properties",
    "BindSmartBean.scanName": "ingest.py:merge_live_properties",
    "BindSmartBean.subType": "ingest.py:merge_live_properties",
    "BoxAc.acpsp": "ingest.py:merge_live_properties",
    "BoxAc.bi": "ingest.py:merge_live_properties",
    "BoxAc.bp": "ingest.py:merge_live_properties",
    "BoxAc.bs": "ingest.py:merge_live_properties",
    "BoxAc.ip": "ingest.py:merge_live_properties",
    "BoxAc.it": "ingest.py:merge_live_properties",
    "BoxAc.mc": "ingest.py:merge_live_properties",
    "BoxAc.op": "ingest.py:merge_live_properties",
    "BoxAc.ot": "ingest.py:merge_live_properties",
    "BoxAc.rb": "ingest.py:merge_live_properties",
    "BoxAc.sn": "ingest.py:merge_live_properties",
    "BoxAc.ss": "ingest.py:merge_live_properties",
    "BoxAc.trb": "ingest.py:merge_live_properties",
    "BoxBody.ac1": "ingest.py:merge_live_properties",
    "BoxBody.ac2": "ingest.py:merge_live_properties",
    "BoxBody.autoDt": "ingest.py:merge_live_properties",
    "BoxBody.bls": "ingest.py:merge_live_properties",
    "BoxBody.cds": "ingest.py:merge_live_properties",
    "BoxBody.cdsDt": "ingest.py:merge_live_properties",
    "BoxBody.cep": "ingest.py:merge_live_properties",
    "BoxBody.cir": "ingest.py:merge_live_properties",
    "BoxBody.ddt": "ingest.py:merge_live_properties",
    "BoxBody.de": "ingest.py:merge_live_properties",
    "BoxBody.dg": "ingest.py:merge_live_properties",
    "BoxBody.dh": "ingest.py:merge_live_properties",
    "BoxBody.ds": "ingest.py:merge_live_properties",
    "BoxBody.dt": "ingest.py:merge_live_properties",
    "BoxBody.en": "ingest.py:merge_live_properties",
    "BoxBody.f": "ingest.py:merge_live_properties",
    "BoxBody.fz": "ingest.py:merge_live_properties",
    "BoxBody.ip": "ingest.py:merge_live_properties",
    "BoxBody.mac": "ingest.py:merge_live_properties",
    "BoxBody.op": "ingest.py:merge_live_properties",
    "BoxBody.ot": "ingest.py:merge_live_properties",
    "BoxBody.ps": "ingest.py:merge_live_properties",
    "BoxBody.pss": "ingest.py:merge_live_properties",
    "BoxBody.pst": "ingest.py:merge_live_properties",
    "BoxBody.rb": "ingest.py:merge_live_properties",
    "BoxBody.rc": "ingest.py:merge_live_properties",
    "BoxBody.selfDt": "ingest.py:merge_live_properties",
    "BoxBody.storm": "ingest.py:merge_live_properties",
    "BoxBody.ups": "ingest.py:merge_live_properties",
    "BoxBody.wip": "ingest.py:merge_live_properties",
    "BoxBody.wname": "ingest.py:merge_live_properties",
    "BoxBody.wpc": "ingest.py:merge_live_properties",
    "BoxBody.wps": "ingest.py:merge_live_properties",
    "BoxBody.wsig": "ingest.py:merge_live_properties",
    "BoxEleStatApi.path": "stats/__init__.py:normalize_stat_response",
    "BoxEleStatApi.response.total": "stats/__init__.py:normalize_stat_response",
    "BoxEleStatApi.response.unit": "stats/__init__.py:normalize_stat_response",
    "BoxEleStatApi.response.x": "stats/__init__.py:normalize_stat_response",
    "BoxEleStatApi.response.y": "stats/__init__.py:normalize_stat_response",
    "BoxPowerOutageStatApi.path": "stats/__init__.py:normalize_stat_response",
    "BoxPowerOutageStatApi.response.cnt": "stats/__init__.py:normalize_stat_response",
    "BoxPowerOutageStatApi.response.totalInterval": "stats/__init__.py:normalize_stat_response",
    "Circuit.idx": "ingest.py:merge_live_properties",
    "Circuit.nm": "ingest.py:merge_live_properties",
    "Circuit.pc": "ingest.py:merge_live_properties",
    "Circuit.pr": "ingest.py:merge_live_properties",
    "Circuit.sph": "ingest.py:merge_live_properties",
    "Circuit.sph_pc": "ingest.py:merge_live_properties",
    "Circuit.sw": "ingest.py:merge_live_properties",
    "CollectorSub.inPw": "ingest.py:merge_live_properties",
    "CollectorSub.outPw": "ingest.py:merge_live_properties",
    "CollectorSub.wip": "ingest.py:merge_live_properties",
    "CtStatApi.path": "stats/__init__.py:normalize_stat_response",
    "CtStatApi.response.totalInCtEnergy": "stats/__init__.py:normalize_stat_response",
    "CtStatApi.response.totalOutCtEnergy": "stats/__init__.py:normalize_stat_response",
    "CtStatApi.response.unit": "stats/__init__.py:normalize_stat_response",
    "CtStatApi.response.x": "stats/__init__.py:normalize_stat_response",
    "CtStatApi.response.y1": "stats/__init__.py:normalize_stat_response",
    "CtStatApi.response.y2": "stats/__init__.py:normalize_stat_response",
    "CtSub.aPhasePw": "ingest.py:merge_live_properties",
    "CtSub.anPhasePw": "ingest.py:merge_live_properties",
    "CtSub.bPhasePw": "ingest.py:merge_live_properties",
    "CtSub.bnPhasePw": "ingest.py:merge_live_properties",
    "CtSub.cPhasePw": "ingest.py:merge_live_properties",
    "CtSub.cnPhasePw": "ingest.py:merge_live_properties",
    "CtSub.funForm": "ingest.py:merge_live_properties",
    "CtSub.schePhase": "ingest.py:merge_live_properties",
    "CtSub.tPhasePw": "ingest.py:merge_live_properties",
    "CtSub.tnPhasePw": "ingest.py:merge_live_properties",
    "CtSub.wip": "ingest.py:merge_live_properties",
    "DeviceChargeReportApi.path": "stats/__init__.py:normalize_stat_response",
    "DeviceChargeReportApi.response_item.chargeInterval": "stats/__init__.py:normalize_stat_response",
    "DeviceChargeReportApi.response_item.deviceSn": "stats/__init__.py:normalize_stat_response",
    "DeviceChargeReportApi.response_item.endSoc": "stats/__init__.py:normalize_stat_response",
    "DeviceChargeReportApi.response_item.endTs": "stats/__init__.py:normalize_stat_response",
    "DeviceChargeReportApi.response_item.id": "stats/__init__.py:normalize_stat_response",
    "DeviceChargeReportApi.response_item.maxPower": "stats/__init__.py:normalize_stat_response",
    "DeviceChargeReportApi.response_item.startSoc": "stats/__init__.py:normalize_stat_response",
    "DeviceChargeReportApi.response_item.startTs": "stats/__init__.py:normalize_stat_response",
    "DeviceChargeReportApi.response_item.totalEnergy": "stats/__init__.py:normalize_stat_response",
    "DeviceStatDeviceStatistic.path": "stats/__init__.py:normalize_stat_response",
    "DeviceStatDeviceStatistic.response.batChgEgy": "stats/__init__.py:normalize_stat_response",
    "DeviceStatDeviceStatistic.response.batDisChgEgy": "stats/__init__.py:normalize_stat_response",
    "DeviceStatDeviceStatistic.response.inEpsEgy": "stats/__init__.py:normalize_stat_response",
    "DeviceStatDeviceStatistic.response.inOngridEgy": "stats/__init__.py:normalize_stat_response",
    "DeviceStatDeviceStatistic.response.outEpsEgy": "stats/__init__.py:normalize_stat_response",
    "DeviceStatDeviceStatistic.response.outOngridEgy": "stats/__init__.py:normalize_stat_response",
    "DeviceStatDeviceStatistic.response.pvEgy": "stats/__init__.py:normalize_stat_response",
    "DeviceStatSocApi.path": "stats/__init__.py:normalize_stat_response",
    "DeviceStatSocApi.response.x": "stats/__init__.py:normalize_stat_response",
    "DeviceStatSocApi.response.y1": "stats/__init__.py:normalize_stat_response",
    "DeviceStatSocketStatistic.path": "stats/__init__.py:normalize_stat_response",
    "DeviceStatSocketStatistic.response.todayEgy": "stats/__init__.py:normalize_stat_response",
    "DeviceStatSocketStatistic.response.totalEgy": "stats/__init__.py:normalize_stat_response",
    "DeviceStatSystemStatistic.path": "stats/__init__.py:normalize_stat_response",
    "DeviceStatSystemStatistic.response.isSetPrice": "stats/__init__.py:normalize_stat_response",
    "DeviceStatSystemStatistic.response.todayBatteryChg": "stats/__init__.py:normalize_stat_response",
    "DeviceStatSystemStatistic.response.todayBatteryDisChg": "stats/__init__.py:normalize_stat_response",
    "DeviceStatSystemStatistic.response.todayGeneration": "stats/__init__.py:normalize_stat_response",
    "DeviceStatSystemStatistic.response.todayLoad": "stats/__init__.py:normalize_stat_response",
    "DeviceStatSystemStatistic.response.totalCarbon": "stats/__init__.py:normalize_stat_response",
    "DeviceStatSystemStatistic.response.totalGeneration": "stats/__init__.py:normalize_stat_response",
    "DeviceStatSystemStatistic.response.totalRevenue": "stats/__init__.py:normalize_stat_response",
    "EpsStatApi.path": "stats/__init__.py:normalize_stat_response",
    "EpsStatApi.response.totalInEpsEnergy": "stats/__init__.py:normalize_stat_response",
    "EpsStatApi.response.totalOutEpsEnergy": "stats/__init__.py:normalize_stat_response",
    "EpsStatApi.response.unit": "stats/__init__.py:normalize_stat_response",
    "EpsStatApi.response.x": "stats/__init__.py:normalize_stat_response",
    "EpsStatApi.response.y": "stats/__init__.py:normalize_stat_response",
    "EpsStatApi.response.y1": "stats/__init__.py:normalize_stat_response",
    "EpsStatApi.response.y2": "stats/__init__.py:normalize_stat_response",
    "Fault.bs1": "ingest.py:merge_live_properties",
    "Fault.bs2": "ingest.py:merge_live_properties",
    "Fault.ec1": "ingest.py:merge_live_properties",
    "Fault.ec2": "ingest.py:merge_live_properties",
    "Fault.es": "ingest.py:merge_live_properties",
    "Fault.gs": "ingest.py:merge_live_properties",
    "Fault.loc": "ingest.py:merge_live_properties",
    "Fault.moc": "ingest.py:merge_live_properties",
    "Fault.ntc": "ingest.py:merge_live_properties",
    "Fault.ol": "ingest.py:merge_live_properties",
    "Fault.ta1": "ingest.py:merge_live_properties",
    "Fault.ta2": "ingest.py:merge_live_properties",
    "HomeAlarmBody.alarmId": "ingest.py:merge_live_properties",
    "HomeAlarmBody.subDevice": "ingest.py:merge_live_properties",
    "HomeAlarmBody.sysAlertCount": "ingest.py:merge_live_properties",
    "HomeBody.ability": "ingest.py:merge_live_properties",
    "HomeBody.autoStandby": "ingest.py:merge_live_properties",
    "HomeBody.batInPw": "ingest.py:merge_live_properties",
    "HomeBody.batNum": "ingest.py:merge_live_properties",
    "HomeBody.batOutPw": "ingest.py:merge_live_properties",
    "HomeBody.batSoc": "ingest.py:merge_live_properties",
    "HomeBody.cellTemp": "ingest.py:merge_live_properties",
    "HomeBody.eip": "ingest.py:merge_live_properties",
    "HomeBody.emac": "ingest.py:merge_live_properties",
    "HomeBody.ethPort": "ingest.py:merge_live_properties",
    "HomeBody.f": "ingest.py:merge_live_properties",
    "HomeBody.inOngridPw": "ingest.py:merge_live_properties",
    "HomeBody.mac": "ingest.py:merge_live_properties",
    "HomeBody.maxGridStdPw": "ingest.py:merge_live_properties",
    "HomeBody.maxInvStdPw": "ingest.py:merge_live_properties",
    "HomeBody.maxIotNum": "ingest.py:merge_live_properties",
    "HomeBody.maxOutPw": "ingest.py:merge_live_properties",
    "HomeBody.ongridStat": "ingest.py:merge_live_properties",
    "HomeBody.outOngridPw": "ingest.py:merge_live_properties",
    "HomeBody.pv1": "ingest.py:merge_live_properties",
    "HomeBody.pv2": "ingest.py:merge_live_properties",
    "HomeBody.pv3": "ingest.py:merge_live_properties",
    "HomeBody.pv4": "ingest.py:merge_live_properties",
    "HomeBody.pvPw": "ingest.py:merge_live_properties",
    "HomeBody.reboot": "ingest.py:merge_live_properties",
    "HomeBody.socChgLimit": "ingest.py:merge_live_properties",
    "HomeBody.socDischgLimit": "ingest.py:merge_live_properties",
    "HomeBody.swEps": "ingest.py:merge_live_properties",
    "HomeBody.swEpsInPw": "ingest.py:merge_live_properties",
    "HomeBody.swEpsOutPw": "ingest.py:merge_live_properties",
    "HomeBody.swEpsState": "ingest.py:merge_live_properties",
    "HomeBody.wip": "ingest.py:merge_live_properties",
    "HomeBody.wname": "ingest.py:merge_live_properties",
    "HomeBody.wsig": "ingest.py:merge_live_properties",
    "HomeStatApi.path": "stats/__init__.py:normalize_stat_response",
    "HomeStatApi.response.totalInGridEnergy": "stats/__init__.py:normalize_stat_response",
    "HomeStatApi.response.totalOutGridEnergy": "stats/__init__.py:normalize_stat_response",
    "HomeStatApi.response.unit": "stats/__init__.py:normalize_stat_response",
    "HomeStatApi.response.x": "stats/__init__.py:normalize_stat_response",
    "HomeStatApi.response.y": "stats/__init__.py:normalize_stat_response",
    "HomeStatApi.response.y1": "stats/__init__.py:normalize_stat_response",
    "HomeStatApi.response.y2": "stats/__init__.py:normalize_stat_response",
    "MqttBean.body": "ingest.py:merge_live_properties",
    "MqttBean.deviceSn": "ingest.py:merge_live_properties",
    "MqttBody.expireTimestamp": "ingest.py:merge_live_properties",
    "MqttBody.online": "ingest.py:merge_live_properties",
    "MqttBody.status": "ingest.py:merge_live_properties",
    "MqttBody.subDevices": "ingest.py:merge_live_properties",
    "PV.commState": "ingest.py:merge_live_properties",
    "PV.name": "ingest.py:merge_live_properties",
    "PV.pvPw": "ingest.py:merge_live_properties",
    "Plan.et": "ingest.py:merge_live_properties",
    "Plan.lps": "ingest.py:merge_live_properties",
    "Plan.pid": "ingest.py:merge_live_properties",
    "Plan.st": "ingest.py:merge_live_properties",
    "Plan.sw": "ingest.py:merge_live_properties",
    "Plan.tt": "ingest.py:merge_live_properties",
    "PlugSub.inPw": "ingest.py:merge_live_properties",
    "PlugSub.outPw": "ingest.py:merge_live_properties",
    "PlugSub.socketPri": "ingest.py:merge_live_properties",
    "PlugSub.switchSta": "ingest.py:merge_live_properties",
    "PlugSub.sysSwitch": "ingest.py:merge_live_properties",
    "PlugSub.wip": "ingest.py:merge_live_properties",
    "PvStatApi.path": "stats/__init__.py:normalize_stat_response",
    "PvStatApi.response.currency": "stats/__init__.py:normalize_stat_response",
    "PvStatApi.response.totalSolarEnergy": "stats/__init__.py:normalize_stat_response",
    "PvStatApi.response.totalSolarRevenue": "stats/__init__.py:normalize_stat_response",
    "PvStatApi.response.unit": "stats/__init__.py:normalize_stat_response",
    "PvStatApi.response.x": "stats/__init__.py:normalize_stat_response",
    "PvStatApi.response.y": "stats/__init__.py:normalize_stat_response",
    "PvStatApi.response.y1": "stats/__init__.py:normalize_stat_response",
    "PvStatApi.response.y2": "stats/__init__.py:normalize_stat_response",
    "PvStatApi.response.y3": "stats/__init__.py:normalize_stat_response",
    "PvStatApi.response.y4": "stats/__init__.py:normalize_stat_response",
    "SocialContributionsApi.path": "stats/__init__.py:normalize_stat_response",
    "SocialContributionsApi.response.co2": "stats/__init__.py:normalize_stat_response",
    "SocialContributionsApi.response.coal": "stats/__init__.py:normalize_stat_response",
    "SocialContributionsApi.response.tree": "stats/__init__.py:normalize_stat_response",
    "StatProfitApi.path": "stats/__init__.py:normalize_stat_response",
    "StatProfitApi.response.currency": "stats/__init__.py:normalize_stat_response",
    "StatProfitApi.response.total": "stats/__init__.py:normalize_stat_response",
    "SubAlarm.alertCount": "ingest.py:merge_live_properties",
    "SubAlarm.devType": "ingest.py:merge_live_properties",
    "SubAlarm.deviceSn": "ingest.py:merge_live_properties",
    "SubBaseBean.bindKey": "ingest.py:merge_live_properties",
    "SubBaseBean.commMode": "ingest.py:merge_live_properties",
    "SubBaseBean.commState": "ingest.py:merge_live_properties",
    "SubBaseBean.deviceName": "ingest.py:merge_live_properties",
    "SubBaseBean.deviceSn": "ingest.py:merge_live_properties",
    "SubBaseBean.scanName": "ingest.py:merge_live_properties",
    "SubBaseBean.subType": "ingest.py:merge_live_properties",
    "SysBatteryStatApi.path": "stats/__init__.py:normalize_stat_response",
    "SysBatteryStatApi.response.batterySources": "stats/__init__.py:normalize_stat_response",
    "SysBatteryStatApi.response.batteryUsage": "stats/__init__.py:normalize_stat_response",
    "SysBatteryStatApi.response.totalChgEgy": "stats/__init__.py:normalize_stat_response",
    "SysBatteryStatApi.response.totalDisChgEgy": "stats/__init__.py:normalize_stat_response",
    "SysBatteryStatApi.response.unit": "stats/__init__.py:normalize_stat_response",
    "SysBatteryStatApi.response.x": "stats/__init__.py:normalize_stat_response",
    "SysBatteryStatApi.response.y": "stats/__init__.py:normalize_stat_response",
    "SysBatteryStatApi.response.y1": "stats/__init__.py:normalize_stat_response",
    "SysBatteryStatApi.response.y2": "stats/__init__.py:normalize_stat_response",
    "SysHomeStatApi.path": "stats/__init__.py:normalize_stat_response",
    "SysHomeStatApi.response.homeSources": "stats/__init__.py:normalize_stat_response",
    "SysHomeStatApi.response.totalHomeEgy": "stats/__init__.py:normalize_stat_response",
    "SysHomeStatApi.response.unit": "stats/__init__.py:normalize_stat_response",
    "SysHomeStatApi.response.x": "stats/__init__.py:normalize_stat_response",
    "SysHomeStatApi.response.y": "stats/__init__.py:normalize_stat_response",
    "SysPvStatApi.path": "stats/__init__.py:normalize_stat_response",
    "SysPvStatApi.response.count": "stats/__init__.py:normalize_stat_response",
    "SysPvStatApi.response.currency": "stats/__init__.py:normalize_stat_response",
    "SysPvStatApi.response.pvSources": "stats/__init__.py:normalize_stat_response",
    "SysPvStatApi.response.pvUsage": "stats/__init__.py:normalize_stat_response",
    "SysPvStatApi.response.showDash": "stats/__init__.py:normalize_stat_response",
    "SysPvStatApi.response.totalSolarEnergy": "stats/__init__.py:normalize_stat_response",
    "SysPvStatApi.response.totalSolarRevenue": "stats/__init__.py:normalize_stat_response",
    "SysPvStatApi.response.unit": "stats/__init__.py:normalize_stat_response",
    "SysPvStatApi.response.weather": "stats/__init__.py:normalize_stat_response",
    "SysPvStatApi.response.x": "stats/__init__.py:normalize_stat_response",
    "SysPvStatApi.response.y": "stats/__init__.py:normalize_stat_response",
    "SystemBody.batInPw": "ingest.py:merge_live_properties",
    "SystemBody.batNum": "ingest.py:merge_live_properties",
    "SystemBody.batOutPw": "ingest.py:merge_live_properties",
    "SystemBody.batState": "ingest.py:merge_live_properties",
    "SystemBody.ctStat": "ingest.py:merge_live_properties",
    "SystemBody.defaultPw": "ingest.py:merge_live_properties",
    "SystemBody.energyPlanPw": "ingest.py:merge_live_properties",
    "SystemBody.funcEnable": "ingest.py:merge_live_properties",
    "SystemBody.gridInPw": "ingest.py:merge_live_properties",
    "SystemBody.gridOutPw": "ingest.py:merge_live_properties",
    "SystemBody.gridSate": "ingest.py:merge_live_properties",
    "SystemBody.inGridSidePw": "ingest.py:merge_live_properties",
    "SystemBody.isAutoStandby": "ingest.py:merge_live_properties",
    "SystemBody.isFollowMeterPw": "ingest.py:merge_live_properties",
    "SystemBody.maxFeedGrid": "ingest.py:merge_live_properties",
    "SystemBody.maxSysInPw": "ingest.py:merge_live_properties",
    "SystemBody.maxSysOutPw": "ingest.py:merge_live_properties",
    "SystemBody.offGridDown": "ingest.py:merge_live_properties",
    "SystemBody.offGridTime": "ingest.py:merge_live_properties",
    "SystemBody.ongridStat": "ingest.py:merge_live_properties",
    "SystemBody.otherLoadPw": "ingest.py:merge_live_properties",
    "SystemBody.outGridSidePw": "ingest.py:merge_live_properties",
    "SystemBody.soc": "ingest.py:merge_live_properties",
    "SystemBody.standbyPw": "ingest.py:merge_live_properties",
    "SystemBody.stat": "ingest.py:merge_live_properties",
    "SystemBody.swEpsInPw": "ingest.py:merge_live_properties",
    "SystemBody.swEpsOutPw": "ingest.py:merge_live_properties",
    "SystemBody.tempUnit": "ingest.py:merge_live_properties",
    "SystemBody.workModel": "ingest.py:merge_live_properties",
    "SystemBody.wpc": "ingest.py:merge_live_properties",
    "SystemBody.wps": "ingest.py:merge_live_properties",
    "ThirdPartyMqttBody.enable": "ingest.py:merge_live_properties",
    "ThirdPartyMqttBody.ip": "ingest.py:merge_live_properties",
    "ThirdPartyMqttBody.password": "ingest.py:merge_live_properties",
    "ThirdPartyMqttBody.port": "ingest.py:merge_live_properties",
    "ThirdPartyMqttBody.token": "ingest.py:merge_live_properties",
    "ThirdPartyMqttBody.userName": "ingest.py:merge_live_properties",
    "TodayEnergyApi.note": "stats/__init__.py:normalize_stat_response",
    "TodayEnergyApi.path": "stats/__init__.py:normalize_stat_response",
    "TodayEnergyApi.response.de": "stats/__init__.py:normalize_stat_response",
    "TodayEnergyApi.response.dg": "stats/__init__.py:normalize_stat_response",
    "TodayEnergyApi.response.dh": "stats/__init__.py:normalize_stat_response",
    "TodayEnergyApi.response.ds": "stats/__init__.py:normalize_stat_response",
    "WifiBean.r": "ingest.py:merge_live_properties",
    "WifiBean.s": "ingest.py:merge_live_properties",
}

DTO_FIELD_EXEMPTIONS: Final[dict[str, str]] = {
    "PeaksTroughs.*": "Portable-app TOU DTO; SolarVault uses cloud TOU endpoints instead.",
    "PeaksTroughsTask.*": "Portable-app TOU task DTO; SolarVault uses cloud TOU endpoints "
    "instead.",
    "PortableBody.*": "Mobile app portable power-station DTO; SolarVault home entities "
    "intentionally do not consume portable-only fields.",
    "Storm.*": "Mobile weather/storm automation DTO; not a Home Assistant entity source.",
}
