name: Auto-merge Dependabot
on: pull_request

concurrency:
  group: auto-mergen-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: 
  contents: write # for actions/checkout, if you're in a private repo
  pull-requests: write
  actions: write
  checks: write
  id-token: write # for Trusted Publishing + attest-action
  
jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
