name: Dependency Review

on:
  push:
  pull_request:
    branches-ignore:
      - "autofix/**"

permissions:
  contents: write
  actions: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Dependency Review
        uses: actions/dependency-review-action@v5.0.0
