name: Pre-commit Lite

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write # for actions/checkout, if you're in a private repo
  pull-requests: write
  actions: write
  checks: write
  id-token: write # for Trusted Publishing + attest-action
  
concurrency:
  group: pre-commit-lite-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      PYTHON_VERSION: ${{ vars.PYTHON_VERSION != '' && vars.PYTHON_VERSION || '3.14' }}
      HA_SPEC: ${{ vars.HA_VERSION != '' && format('=={0}', vars.HA_VERSION) || '' }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          # Value already defaults to true, but `persist-credentials` is required to push new commits to the repository.
          persist-credentials: true
          
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache-dependency-path: |
            requirements.txt
            requirements-test.txt
            pyproject.toml
            
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          #enable-cache: true
          #ignore-nothing-to-cache: true
          
      - uses: astral-sh/ruff-action@v4.0.0
      - uses: actions/setup-python@v4
        with:
           python-version: 3.14
      - run: ruff check . --fix
      - run: ruff format .
      - run: ruff check . --fix --preview --target-version py314 || true
      - run: ruff format . || true
      - uses: pre-commit/action@v3.0.1
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v7
