name: release-please
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  issues: write
  contents: write # for actions/checkout, if you're in a private repo
  pull-requests: write
  actions: write
  checks: write
  id-token: write # for Trusted Publishing + attest-action

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # oder RELEASE_PLEASE_TOKEN (PAT)
          release-type: simple
